### ISSUE TITLE
If year range is less than number of ticks, ticks are repeated

### ISSUE THREAD

**Issue by alexandersimoes** [d3plus/d3plus-timeline#13]
![screen shot 2016-12-20 at 6 40 28 pm](https://cloud.githubusercontent.com/assets/252276/21372228/f297f04c-c6e3-11e6-9c17-36a78942d152.png)

**Comment by davelandry** [comment]
@alexandersimoes this was actually a result of the time formatter being passed from Pantheon for the timeline 😮
