### ISSUE TITLE
Selecting a DOM element fails to render correctly

### ISSUE THREAD

**Issue by connorjrice** [d3plus/d3plus-timeline#28]
https://jsfiddle.net/7sd60eb4/

The only portion of the figure that renders is the domain.

**Comment by connorjrice** [comment]
Having an SVG element inside of the div worked, following the example from d3plus-axis:
https://jsfiddle.net/7sd60eb4/2/

**Comment by davelandry** [comment]
@connorjrice yes, as of right now the selector passed to the `select` method needs to be an SVG, or a group inside of an SVG.
