### ISSUE TITLE
Problem with Timeline render

### ISSUE THREAD

**Issue by palamago** [d3plus/d3plus-timeline#47]
Weird rendering when dates comes from different year-months.

### Expected Behavior
Behavior is ok. It renders 4 options (my 4 different dates) and on click the viz changes properly.
The problem is in presentation and formatting.

### Current Behavior
Timelie is shown like this:
![captura de pantalla 2018-12-10 a la s 16 38 54](https://user-images.githubusercontent.com/1203432/49757201-992fa600-fc9a-11e8-8e0e-2b9ab548b600.png)

Why are they rotated? How can I format this strings in the timeline (I need to show quarters)?

### Steps to Reproduce (for bugs)
1. See timeline here: https://jsfiddle.net/palamago/d46qae3v/

### Your Environment
* Browser Name: Chrome
* Operating System and Version:

**Comment by davelandry** [comment]
@cnavarreteliz can you look into why this is happening?

**Comment by cnavarreteliz** [comment]
Sure @davelandry !

**Comment by jspeis** [comment]
Thanks guys! if the issue is fixed, would we be able to get a new release? :)

**Comment by davelandry** [comment]
@cnavarreteliz was able to get the needed underlying behavior into `d3plus-axis`, but there's still some bug testing needed in `d3plus-timeline`: https://github.com/d3plus/d3plus-timeline/pull/48

**Comment by jspeis** [comment]
Awesome, thanks guys!
