### ISSUE TITLE
support locale method for international time formatting

### ISSUE THREAD

**Issue by davelandry** [d3plus/d3plus-timeline#54]

**Comment by cnavarreteliz** [comment]
@davelandry I've been testing, and if you include `.locale("es-ES")` in your timeline configuration, the time labels are updated correctly. 

Link: [https://jsfiddle.net/tjb2s1ea/1/](https://jsfiddle.net/tjb2s1ea/1/)

```
  new d3plus.Timeline()
    .domain([2007, 2010])
    .buttonBehavior("ticks")
    .locale("es-ES")
    .render();
```
