### ISSUE TITLE
improve performance timeline axis

### ISSUE THREAD

**Issue by cnavarreteliz** [d3plus/d3plus-timeline#55]
I want to improve how to manipulate the timeline properties for projects with months / quarters / years, and too much labels in small sizes.

Some ideas:

- Set specific behaviors, like `.timelineBehavior("Quarter")` for quarters.
- Try to improve buttonBehavior

**Comment by davelandry** [comment]
@cnavarreteliz can you give examples of how the timeline is currently behaving?

**Comment by davelandry** [comment]
Solved in https://github.com/d3plus/d3plus-timeline/commit/2196eaea3e2c2598286981c499f46998616a8fa9
